name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: 0 1 * * MON
  workflow_dispatch:

jobs:
  git:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: false
    - id: repo-key
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m")"
    - uses: actions/cache@v2
      id: wsl2_repo
      with:
        path: wsl2-repo
        key: ${{ steps.repo-key.outputs.date }}
    - name: git
      if: steps.wsl2_repo.outputs.cache-hit != 'true'
      run: |
        set -x
        ./git-prepare.sh
        du -sh wsl2-repo
        df -h
  kernel:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: kbuild.image
      run: |
        make kbuild.image
    - name: kbuild.kernel
      run: |
        echo make kbuild.build
    - name: kbuild.ccache
      run: |
        set -x
        make kbuild.ccache-init
        make kbuild.ccache CPU_CORES=2
        du -sh .ccache
