name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: 0 1 * * MON
  workflow_dispatch:

jobs:
  git:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: false
    - name: ID
      id: repo-key
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m")"
    - name: git-cache
      uses: actions/cache@v2
      id: wsl2_repo
      with:
        path: wsl2-repo.git
        key: wsl2-repo.git-${{ steps.repo-key.outputs.date }}
        restore-keys: |
          wsl2-repo.git-${{ steps.repo-key.outputs.date }}
          wsl2-repo.git
    - name: git-init
      if: steps.wsl2_repo.outputs.cache-hit != 'true'
      run: make repo_init

  kernel:
    runs-on: ubuntu-latest
    needs: git
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: false
    - name: kbuild.image
      run: |
        set -x
        image=$(make kbuild.image_print)
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$GITHUB_REPOSITORY/$image
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        old_id=''
        if docker pull $IMAGE_ID; then
          old_id=$(docker image inspect $IMAGE_ID --format "{{.ID}}")
        fi
        make kbuild.image DOCKER_BUILD_OPTS="--cache-from=$IMAGE_ID"
        new_id=$(docker image inspect $image --format "{{.ID}}")
        if [ "$old_id" != "$new_id" ]; then
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag $image $IMAGE_ID:latest
          docker push $IMAGE_ID:latest || true
          rm -rf ~/.docker
        fi
    - name: ccache
      uses: actions/cache@v2
      id: wsl2_ccache
      with:
        path: .ccache
        key: wsl2-ccache-${{ hashFiles('Makefile','custom_config.sh') }}
        restore-keys: |
          wsl2-ccache-${{ hashFiles('Makefile','custom_config.sh') }}
          wsl2-ccache
    - name: ccache.init
      if: steps.wsl2_ccache.outputs.cache-hit != 'true'
      run: make kbuild.ccache-init
    - name: repo
      uses: actions/cache@v2
      id: wsl2_repo
      with:
        path: wsl2-repo.git
        key: wsl2-repo.git-${{ hashFiles('repo.sh') }}
        restore-keys: |
          wsl2-repo.git-${{ hashFiles('repo.sh') }}
          wsl2-repo.git
    - name: wsl-init
      if: steps.wsl2_repo.outputs.cache-hit != 'true'
      run: make repo_init
    - name: wsl-update
      run: make linux-msft-4.19.128.repo_update
    - name: kbuild.config
      run: make configure
    - name: kbuild.ccache
      run: make kbuild.ccache </dev/null
