name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: 0 1 * * MON
  workflow_dispatch:

jobs:
  kernel:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: kbuild.image
      run: |
        make kbuild.image
    - name: git
      run: |
        set -x
        ./git-prepare.sh
        df -h
    - name: kbuild.kernel
      run: |
        make kbuild.build
    - name: kbuild.ccache
      run: |
        set -x
        make kbuild.ccache-init
        make kbuild.ccache
        du -sh .ccache
